### ISSUE TITLE
JSON error in Claude Desktop with fetch server

### ISSUE THREAD

**Issue by martinbechard** [modelcontextprotocol/servers#133]
**Describe the bug**
Getting an error connection Claude Desktop (latest) to fetch server (latest run with uvx)

The error is in Claude Desktop:
2024-11-30T05:16:44.543Z [error] Error in MCP connection to server fetch: SyntaxError: Unexpected token ', "... is not valid JSON
    at JSON.parse (<anonymous>)
    at Vwe (/Applications/Claude.app/Contents/Resources/app.asar/.vite/build/index.js:52:189)
    at qwe.readMessage (/Applications/Claude.app/Contents/Resources/app.asar/.vite/build/index.js:52:115)
    at Gwe.processReadBuffer (/Applications/Claude.app/Contents/Resources/app.asar/.vite/build/index.js:53:1729)
    at Socket.<anonymous> (/Applications/Claude.app/Contents/Resources/app.asar/.vite/build/index.js:53:1520)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at Pipe.onStreamRead (node:internal/stream_base_commons:191:23)

**To Reproduce**
Configure fetch server in Claude Desktop, the error happens right away.
I am also using filesystem which is loading fine. 

Shortly after this error, I get the following error in the fetch server:
==> /Users/martinbechard/Library/Logs/Claude/mcp-server-fetch.log <==
  + Exception Group Traceback (most recent call last):
  |   File "/private/tmp/uvx-mcp-server-fetch/lib/python3.11/site-packages/mcp/server/stdio.py", line 83, in stdio_server
  |     yield read_stream, write_stream
  |   File "/private/tmp/uvx-mcp-server-fetch/lib/python3.11/site-packages/mcp_server_fetch/server.py", line 270, in serve
  |     await server.run(read_stream, write_stream, options, raise_exceptions=True)
  |   File "/private/tmp/uvx-mcp-server-fetch/lib/python3.11/site-packages/mcp/server/__init__.py", line 404, in run
  |     async with ServerSession(
  |   File "/private/tmp/uvx-mcp-server-fetch/lib/python3.11/site-packages/mcp/shared/session.py", line 122, in __aexit__
  |     return await self._task_group.__aexit__(exc_type, exc_val, exc_tb)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/private/tmp/uvx-mcp-server-fetch/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 763, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/private/tmp/uvx-mcp-server-fetch/lib/python3.11/site-packages/mcp/shared/session.py", line 235, in _receive_loop
    |     notification = self._receive_notification_type.model_validate(
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/private/tmp/uvx-mcp-server-fetch/lib/python3.11/site-packages/pydantic/main.py", line 627, in model_validate
    |     return cls.__pydantic_validator__.validate_python(
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    | pydantic_core._pydantic_core.ValidationError: 5 validation errors for ClientNotification
ProgressNotification.method
  Input should be 'notifications/progress' [type=literal_error, input_value='cancelled', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/literal_error
ProgressNotification.params.progressToken
  Field required [type=missing, input_value={'requestId': 0, 'reason'... -2: Request timed out'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
ProgressNotification.params.progress
  Field required [type=missing, input_value={'requestId': 0, 'reason'... -2: Request timed out'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
InitializedNotification.method
  Input should be 'notifications/initialized' [type=literal_error, input_value='cancelled', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/literal_error
RootsListChangedNotification.method
  Input should be 'notifications/roots/list_changed' [type=literal_error, input_value='cancelled', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/literal_error
    +------------------------------------

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "/tmp/uvx-mcp-server-fetch/bin/mcp-server-fetch", line 8, in <module>
  |     sys.exit(main())
  |              ^^^^^^
  |   File "/private/tmp/uvx-mcp-server-fetch/lib/python3.11/site-packages/mcp_server_fetch/__init__.py", line 20, in main
  |     asyncio.run(serve(args.user_agent, args.ignore_robots_txt))
  |   File "/opt/homebrew/Cellar/python@3.11/3.11.10/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
  |     return runner.run(main)
  |            ^^^^^^^^^^^^^^^^
  |   File "/opt/homebrew/Cellar/python@3.11/3.11.10/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
  |     return self._loop.run_until_complete(task)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/opt/homebrew/Cellar/python@3.11/3.11.10/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
  |     return future.result()
  |            ^^^^^^^^^^^^^^^
  |   File "/private/tmp/uvx-mcp-server-fetch/lib/python3.11/site-packages/mcp_server_fetch/server.py", line 269, in serve
  |     async with stdio_server() as (read_stream, write_stream):
  |   File "/opt/homebrew/Cellar/python@3.11/3.11.10/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 231, in __aexit__
  |     await self.gen.athrow(typ, value, traceback)
  |   File "/private/tmp/uvx-mcp-server-fetch/lib/python3.11/site-packages/mcp/server/stdio.py", line 80, in stdio_server
  |     async with anyio.create_task_group() as tg:
  |   File "/private/tmp/uvx-mcp-server-fetch/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 763, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Exception Group Traceback (most recent call last):
    |   File "/private/tmp/uvx-mcp-server-fetch/lib/python3.11/site-packages/mcp/server/stdio.py", line 83, in stdio_server
    |     yield read_stream, write_stream
    |   File "/private/tmp/uvx-mcp-server-fetch/lib/python3.11/site-packages/mcp_server_fetch/server.py", line 270, in serve
    |     await server.run(read_stream, write_stream, options, raise_exceptions=True)
    |   File "/private/tmp/uvx-mcp-server-fetch/lib/python3.11/site-packages/mcp/server/__init__.py", line 404, in run
    |     async with ServerSession(
    |   File "/private/tmp/uvx-mcp-server-fetch/lib/python3.11/site-packages/mcp/shared/session.py", line 122, in __aexit__
    |     return await self._task_group.__aexit__(exc_type, exc_val, exc_tb)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/private/tmp/uvx-mcp-server-fetch/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 763, in __aexit__
    |     raise BaseExceptionGroup(
    | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
    +-+---------------- 1 ----------------
      | Traceback (most recent call last):
      |   File "/private/tmp/uvx-mcp-server-fetch/lib/python3.11/site-packages/mcp/shared/session.py", line 235, in _receive_loop
      |     notification = self._receive_notification_type.model_validate(
      |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      |   File "/private/tmp/uvx-mcp-server-fetch/lib/python3.11/site-packages/pydantic/main.py", line 627, in model_validate
      |     return cls.__pydantic_validator__.validate_python(
      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      | pydantic_core._pydantic_core.ValidationError: 5 validation errors for ClientNotification
ProgressNotification.method
  Input should be 'notifications/progress' [type=literal_error, input_value='cancelled', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/literal_error
ProgressNotification.params.progressToken
  Field required [type=missing, input_value={'requestId': 0, 'reason'... -2: Request timed out'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
ProgressNotification.params.progress
  Field required [type=missing, input_value={'requestId': 0, 'reason'... -2: Request timed out'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
InitializedNotification.method
  Input should be 'notifications/initialized' [type=literal_error, input_value='cancelled', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/literal_error
RootsListChangedNotification.method
  Input should be 'notifications/roots/list_changed' [type=literal_error, input_value='cancelled', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/literal_error
      +------------------------------------

**Comment by wonderwhy-er** [comment]
I was exploring MCPs today
Created this repo https://github.com/wonderwhy-er/ClaudeComputerCommander

And with two MCPs in my config like this
```
{
  "mcpServers": {
    "filesystem": {
      "command": "npx",
      "args": [
        "-y",
        "@modelcontextprotocol/server-filesystem",
        "/Users/eduardruzga/work"
      ]
    },
    "terminal": {
      "command": "sh",
      "args": [
        "-c",
        "cd /Users/eduardruzga/work/ClaudeServerCommander && npm run start"
      ]
    }
  }
}
```

I do get issues that sometimes MCPs do not load and in logs
~/Library/Logs/Claude/mcp.log
 I see errors like
```
2024-12-04T12:49:49.902Z [error] Error in MCP connection to server terminal: SyntaxError: Unexpected token '>', "> tsc && s"... is not valid JSON
    at JSON.parse (<anonymous>)
    at Jbe (/Applications/Claude.app/Contents/Resources/app.asar/.vite/build/index.js:52:189)
    at Xbe.readMessage (/Applications/Claude.app/Contents/Resources/app.asar/.vite/build/index.js:52:115)
    at t0e.processReadBuffer (/Applications/Claude.app/Contents/Resources/app.asar/.vite/build/index.js:53:1842)
    at Socket.<anonymous> (/Applications/Claude.app/Contents/Resources/app.asar/.vite/build/index.js:53:1523)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at Pipe.onStreamRead (node:internal/stream_base_commons:191:23)
```

Not sure I understand what is happening there, not sure its related to fetch server issue.
What I can say is that this error does not help to understand what is happening.
Feels like its trying to parse console logs or something...

**Comment by jspahrsummers** [comment]
> Feels like its trying to parse console logs or something...

@wonderwhy-er MCP servers [should not log to stdout](https://modelcontextprotocol.io/docs/tools/debugging#server-side-logging), as this will interfere with the MCP communication happening there. All logs should go to stderr instead.
