### ISSUE TITLE
Gdrive mcp server

### ISSUE THREAD

**Issue by tagoraiinc** [modelcontextprotocol/servers#203]
Hi All, 

The mcp tools seem to be working fine on Windows now but i am having issues with the mcp gdrive server.

Specifically:
this is my set up":
"gdrive": {
"command": "C:\Program Files\nodejs\node.exe",
"args": [
"C:\Users\shont\AppData\Roaming\npm\node_modules\https://github.com/modelcontextprotocol\server-gdrive\dist\index.js"
]
}

Error: Cannot find module 'C:\C:\Users\shont\AppData\Roaming\npm\node_modules\gcp-oauth.keys.json'
Require stack:

C:\Users\shont\AppData\Roaming\npm\node_modules@modelcontextprotocol\server-gdrive\node_modules@google-cloud\local-auth\build\src\index.js
at Function._resolveFilename (node:internal/modules/cjs/loader:1239:15)
at Function._load (node:internal/modules/cjs/loader:1064:27)
at TracingChannel.traceSync (node:diagnostics_channel:322:14)
at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
at Module.require (node:internal/modules/cjs/loader:1325:12)
at require (node:internal/modules/helpers:136:16)
at authenticate (C:\Users\shont\AppData\Roaming\npm\node_modules@modelcontextprotocol\server-gdrive\node_modules@google-cloud\local-auth\build\src\index.js:49:21)
at authenticateAndSaveCredentials (file:///C:/Users/shont/AppData/Roaming/npm/node_modules/@modelcontextprotocol/server-gdrive/dist/index.js:150:24)
at file:///C:/Users/shont/AppData/Roaming/npm/node_modules/@modelcontextprotocol/server-gdrive/dist/index.js:171:5
at ModuleJob.run (node:internal/modules/esm/module_job:271:25) {
code: 'MODULE_NOT_FOUND',
requireStack: [
'C:\Users\shont\AppData\Roaming\npm\node_modules\https://github.com/modelcontextprotocol\server-gdrive\node_modules\https://github.com/Google-Cloud\local-auth\build\src\index.js'
]
}
(node:22640) [DEP0040] DeprecationWarning: The punycode module is deprecated. Please use a userland alternative instead.
(Use node --trace-deprecation ... to show where the warning was created)

this is the error i get when i try to auth -> ive saved the json key at:  
C:\Users\shont\AppData\Roaming\npm\node_modules\@modelcontextprotocol\server-gdrive

help/advice on fixing, please?

**Comment by jspahrsummers** [comment]
Your args look incorrect here:

`C:\Users\shont\AppData\Roaming\npm\node_modules\https://github.com/modelcontextprotocol\server-gdrive\dist\index.js`

The URL shouldn't be embedded in there.

Can you try changing it to use `npx` now that https://github.com/modelcontextprotocol/servers/issues/40 is fixed on Windows?

**Comment by kevinsalgatar** [comment]
I followed and completed all the steps but gdrive still isn't showing up as a tool

**Comment by tagoraiinc** [comment]
I still have the same problem -- all the other tools working well except for gdrive.  :-(

**Comment by jspahrsummers** [comment]
Ah, I suppose the issue here is that this server isn't going to be compatible with `npx` while it looks for local credentials on disk. 🫤 

A workaround for now would be to clone the repo and `npm link` or `npm install` the server locally. Sorry about the trouble.

**Comment by Utakata** [comment]
```markdown
Thanks for reporting this issue. I also encountered the same problem and found a workaround.

### Current Issue
The server incorrectly tries to find the OAuth key file with a duplicated drive letter prefix:
```javascript
// Current problematic code tries this path:
'C:\C:\Users\...\gcp-oauth.keys.json'
```

### Workaround Steps

1. First build the server:
```bash
cd C:\Users\[YourUsername]\AppData\Roaming\npm\node_modules\@modelcontextprotocol\server-gdrive
npm run build
```

2. Place the OAuth key file directly in the server's directory:
```bash
copy [YOUR_KEY_PATH]\gcp-oauth.keys.json C:\Users\[YourUsername]\AppData\Roaming\npm\node_modules\@modelcontextprotocol\server-gdrive\gcp-oauth.keys.json
```

3. Set the environment variable and run the authentication:
```bash
set GOOGLE_APPLICATION_CREDENTIALS=C:\Users\[YourUsername]\AppData\Roaming\npm\node_modules\@modelcontextprotocol\server-gdrive\gcp-oauth.keys.json
node dist/index.js auth
```

### Long-term Solution Suggestion
The current code:
```javascript
keyfilePath: path.join(path.dirname(new URL(import.meta.url).pathname), "../../../gcp-oauth.keys.json")
```

Could be improved to handle Windows paths better by using:
```javascript
const keyfilePath = path.resolve(process.cwd(), 'gcp-oauth.keys.json');
```

This would provide a more robust solution across different platforms.

### Note
As @jspahrsummers mentioned, this is related to npx compatibility issues. Until a proper fix is implemented, the above workaround should get the server working on Windows systems.
```

**Comment by Utakata** [comment]
Let me create a detailed issue report in English about the GDrive MCP server authentication issue.

# GDrive MCP server won't find credentials when used via `npx` #203

Thanks for reporting this issue. I also encountered the same problem and found a workaround.

### Current Issue
The server incorrectly tries to find the OAuth key file with a duplicated drive letter prefix:
```javascript
// Current problematic code tries this path:
'C:\C:\Users\...\gcp-oauth.keys.json'
```

### Workaround Steps
1. First build the server:
```bash
cd C:\Users\[YourUsername]\AppData\Roaming\npm\node_modules\@modelcontextprotocol\server-gdrive
npm run build
```

2. Place the OAuth key file directly in the server's directory:
```bash
copy [YOUR_KEY_PATH]\gcp-oauth.keys.json C:\Users\[YourUsername]\AppData\Roaming\npm\node_modules\@modelcontextprotocol\server-gdrive\gcp-oauth.keys.json
```

3. Modify the source code (`index.ts`) to fix path resolution:
```javascript
// Old code
const credentialsPath = path.join(
  path.dirname(new URL(import.meta.url).pathname),
  "../../../.gdrive-server-credentials.json"
);

// New code
const credentialsPath = path.resolve(process.cwd(), ".gdrive-server-credentials.json");

// Also modify the authentication function
async function authenticateAndSaveCredentials() {
  console.log("Launching auth flow…");
  const auth = await authenticate({
    keyfilePath: path.resolve(process.cwd(), "gcp-oauth.keys.json"),
    scopes: ["https://www.googleapis.com/auth/drive.readonly"]
  });
  fs.writeFileSync(credentialsPath, JSON.stringify(auth.credentials));
  console.log("Credentials saved. You can now run the server.");
}
```

4. Run the authentication:
```bash
node dist/index.js auth
```

### Configuration for Claude Desktop
Update your `claude_desktop_config.json`:
```json
{
  "mcpServers": {
    "gdrive": {
      "command": "node",
      "args": [
        "C:\\Users\\[YourUsername]\\AppData\\Roaming\\npm\\node_modules\\@modelcontextprotocol\\server-gdrive\\dist\\index.js"
      ]
    }
  }
}
```

### Long-term Solution Suggestion
The current code:
```javascript
keyfilePath: path.join(path.dirname(new URL(import.meta.url).pathname), "../../../gcp-oauth.keys.json")
```

Could be improved to handle Windows paths better by using:
```javascript
const keyfilePath = path.resolve(process.cwd(), 'gcp-oauth.keys.json');
```

This provides a more robust solution across different platforms.

### Note
- This issue is related to Windows path resolution and `npx` compatibility
- The workaround avoids path resolution issues by using absolute paths
- The solution ensures the credentials file is found correctly regardless of how the server is launched
- Using `node` directly instead of `npx` provides more stable operation on Windows

### File Structure After Fix
```
C:\Users\[YourUsername]\AppData\Roaming\npm\node_modules\@modelcontextprotocol\server-gdrive\
├── dist\
│   └── index.js
├── gcp-oauth.keys.json
└── .gdrive-server-credentials.json  # Generated after authentication
```

Please note that this is a temporary workaround until a proper fix is implemented in the upstream package. The long-term solution would involve improving the path resolution logic in the core package.


#!/usr/bin/env node
import { authenticate } from "@google-cloud/local-auth";
import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { CallToolRequestSchema, ListResourcesRequestSchema, ListToolsRequestSchema, ReadResourceRequestSchema } from "@modelcontextprotocol/sdk/types.js";
import fs from "fs";
import { google } from "googleapis";
import path from "path";

const drive = google.drive("v3");
const server = new Server({
    name: "example-servers/gdrive",
    version: "0.1.0",
}, {
    capabilities: {
        resources: {},
        tools: {},
    },
});

// List Resources
server.setRequestHandler(ListResourcesRequestSchema, async (request) => {
    const pageSize = 10;
    const params = {
        pageSize,
        fields: "nextPageToken, files(id, name, mimeType)",
    };
    if (request.params?.cursor) {
        params.pageToken = request.params.cursor;
    }
    const res = await drive.files.list(params);
    const files = res.data.files;
    return {
        resources: files.map((file) => ({
            uri: `gdrive:///${file.id}`,
            mimeType: file.mimeType,
            name: file.name,
        })),
        nextCursor: res.data.nextPageToken,
    };
});

// Read Resource
server.setRequestHandler(ReadResourceRequestSchema, async (request) => {
    const fileId = request.params.uri.replace("gdrive:///", "");
    const file = await drive.files.get({
        fileId,
        fields: "mimeType",
    });
    if (file.data.mimeType?.startsWith("application/vnd.google-apps")) {
        let exportMimeType;
        switch (file.data.mimeType) {
            case "application/vnd.google-apps.document":
                exportMimeType = "text/markdown";
                break;
            case "application/vnd.google-apps.spreadsheet":
                exportMimeType = "text/csv";
                break;
            case "application/vnd.google-apps.presentation":
                exportMimeType = "text/plain";
                break;
            case "application/vnd.google-apps.drawing":
                exportMimeType = "image/png";
                break;
            default:
                exportMimeType = "text/plain";
        }
        const res = await drive.files.export({ fileId, mimeType: exportMimeType }, { responseType: "text" });
        return {
            contents: [
                {
                    uri: request.params.uri,
                    mimeType: exportMimeType,
                    text: res.data,
                },
            ],
        };
    }
    const res = await drive.files.get({ fileId, alt: "media" }, { responseType: "arraybuffer" });
    const mimeType = file.data.mimeType || "application/octet-stream";
    if (mimeType.startsWith("text/") || mimeType === "application/json") {
        return {
            contents: [
                {
                    uri: request.params.uri,
                    mimeType: mimeType,
                    text: Buffer.from(res.data).toString("utf-8"),
                },
            ],
        };
    } else {
        return {
            contents: [
                {
                    uri: request.params.uri,
                    mimeType: mimeType,
                    blob: Buffer.from(res.data).toString("base64"),
                },
            ],
        };
    }
});

// Tools
server.setRequestHandler(ListToolsRequestSchema, async () => {
    return {
        tools: [
            {
                name: "search",
                description: "Search for files in Google Drive",
                inputSchema: {
                    type: "object",
                    properties: {
                        query: {
                            type: "string",
                            description: "Search query",
                        },
                    },
                    required: ["query"],
                },
            },
        ],
    };
});

server.setRequestHandler(CallToolRequestSchema, async (request) => {
    if (request.params.name === "search") {
        const userQuery = request.params.arguments?.query;
        const escapedQuery = userQuery.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
        const formattedQuery = `fullText contains '${escapedQuery}'`;
        const res = await drive.files.list({
            q: formattedQuery,
            pageSize: 10,
            fields: "files(id, name, mimeType, modifiedTime, size)",
        });
        const fileList = res.data.files
            ?.map((file) => `${file.name} (${file.mimeType})`)
            .join("\n");
        return {
            content: [
                {
                    type: "text",
                    text: `Found ${res.data.files?.length ?? 0} files:\n${fileList}`,
                },
            ],
            isError: false,
        };
    }
    throw new Error("Tool not found");
});

const credentialsPath = path.resolve(process.cwd(), ".gdrive-server-credentials.json");

async function authenticateAndSaveCredentials() {
    console.log("Launching auth flow…");
    const auth = await authenticate({
        keyfilePath: path.resolve(process.cwd(), "gcp-oauth.keys.json"),
        scopes: ["https://www.googleapis.com/auth/drive"],
    });
    fs.writeFileSync(credentialsPath, JSON.stringify(auth.credentials));
    console.log("Credentials saved. You can now run the server.");
}

async function loadCredentialsAndRunServer() {
    if (!fs.existsSync(credentialsPath)) {
        console.error("Credentials not found. Please run with 'auth' argument first.");
        process.exit(1);
    }
    const credentials = JSON.parse(fs.readFileSync(credentialsPath, "utf-8"));
    const auth = new google.auth.OAuth2();
    auth.setCredentials(credentials);
    google.options({ auth });
    console.log("Credentials loaded. Starting server.");
    const transport = new StdioServerTransport();
    await server.connect(transport);
}

if (process.argv[2] === "auth") {
    authenticateAndSaveCredentials().catch(console.error);
} else {
    loadCredentialsAndRunServer().catch(console.error);
}
```
