### ISSUE TITLE
MCP server-time does not work on non-English system

### ISSUE THREAD

**Issue by kurtthomas** [modelcontextprotocol/servers#231]
**Describe the bug**
Thank you for server-time.

Attempting to run the server-time MCP fails on a system where time zone names are not in English.

**To Reproduce**
1. Be on a Windows system where English is not the primary OS language.
2. Set local Windows time zone to _(name of MET in local language)_.
Either:
3A Start Claud AI Desktop Agent ==> Cannot connect to MCP server.
/Or/
3A Start mcp-server time with uvx ==> Error (see below)

**Expected behavior**
MCP works.

**Logs**
_uvx command:_
uvx mcp-server-time
_Command error output:_
Traceback (most recent call last):
  File "C:\Users\Kurt\AppData\Local\Programs\Python\Python311\Lib\zoneinfo\_common.py", line 12, in load_tzdata
    return resources.files(package_name).joinpath(resource_name).open("rb")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kurt\AppData\Local\Programs\Python\Python311\Lib\pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Kurt\\AppData\\Local\\uv\\cache\\archive-v0\\ImCvLqiPqR99S_aUJhnZd\\Lib\\site-packages\\tzdata\\zoneinfo\\**Mitteleuropäische Zeit**'

(Emphasis added)

**Additional context**
_Mitteleuropäische Zeit_ is the German / Windows name for "MET".
Workaround is to find the MET file and copy it to <name of time zone in local language>.

**Comment by jspahrsummers** [comment]
This seems like it might be a bug in Python's `zoneinfo` module, as the server doesn't do this part itself.

**Comment by Ranteck** [comment]
still the issue, having the same trouble but in my case i'm using 

`        "time": {
            "command": "uvx",
            "args": [
                "mcp_server_time"
            ]
        },`

**Comment by tjx666** [comment]
Chinese user, doesn't work in cursor 

<img width="453" alt="Image" src="https://github.com/user-attachments/assets/8fbedf82-ce76-475e-8fea-6824e85788bc" />

**Comment by Hawstein** [comment]
Passing the `--local-timezone` argument to the mcp server can fix this issue. In [ClaudeMind](https://claudemind.com/), we obtain the system timezone using `Intl.DateTimeFormat().resolvedOptions().timeZone`, then construct the `--local-timezone=${system_timezone}` argument to pass to the Time MCP Server.

**Comment by Hitec-at** [comment]
> Chinese user, doesn't work in cursor
> 
> <img alt="Image" width="453" src="https://private-user-images.githubusercontent.com/41773861/408420878-8fbedf82-ce76-475e-8fea-6824e85788bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTAzMjAzMjUsIm5iZiI6MTc1MDMyMDAyNSwicGF0aCI6Ii80MTc3Mzg2MS80MDg0MjA4NzgtOGZiZWRmODItY2U3Ni00NzVlLThmZWEtNjgyNGU4NTc4OGJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNjE5VDA4MDAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmNTY1YjNkZjVjYTk2NWY5YjYzNWZhNDRjNmE5YjkyZDZkZjYxMDYxNmFmZTUzZGY4YWI5OWVkMjhmM2MzZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cLZxTZ6Vojr1h2rnFdcCM9Rl3okFv4DDRv-bGIKMgFY">

Same issue on trae MCP and after checking error msgs I found a workaround using `--local-timezone Hongkong`. Full config: 
```
{
  "mcpServers": {
    "Time": {
      "command": "python",
      "args": [
        "-m",
        "mcp_server_time",
        "--local-timezone",
        "Hongkong"
      ],
      "env": {}
    }
  }
}
```

**Comment by domdomegg** [comment]
Sorry about this, and thanks for reporting! I think this is the same underlying cause as #489, so we'll track that over there - we believe this issue has now been fixed.
