### ISSUE TITLE
github server fail to request list_issues

### ISSUE THREAD

**Issue by kzmszk** [modelcontextprotocol/servers#296]
**Describe the bug**
The github mcp server should have supported list_issues command (which is documented) but list_tools doesn't return this tool entry and we can't call it actually.

**To Reproduce**
1. setup claude desktop with server-github
2. request claude to get issues from any repo

or

1. create mcp-client which support github mcp server
2. call list_tools() after connecting github server
3. tools list doesn't contain list_issues tool

or 

1. create mcp-client which support github mcp server
2. call session.call_tool("list_issues",...) fail

**Expected behavior**
list_issues should be available for github_server.

**Logs**
error log from my mcp-client sample bellow:
      | Traceback (most recent call last):
      |   File "/workspace/tachikoma/infra/mcp/github.py", line 34, in list_issues
      |     result = await session.call_tool("list_issues", arguments={"owner": owner, "repo": repo})
      |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      |   File "/opt/.venv/lib/python3.12/site-packages/mcp/client/session.py", line 163, in call_tool
      |     return await self.send_request(
      |            ^^^^^^^^^^^^^^^^^^^^^^^^
      |   File "/opt/.venv/lib/python3.12/site-packages/mcp/shared/session.py", line 175, in send_request
      |     raise McpError(response_or_error.error)
      | mcp.shared.exceptions.McpError: code=-32603 message='Unknown tool: list_issues' data=None

conversation with claude desktop:

The original response is in Japanese. I translated into English. 
Claude responded available github related commands.
```
I'm sorry `list_issues` function seems to be not included in github features.

Availabe GitHub related function is bellow：
- create_or_update_file
- search_repositories
- create_repository
- get_file_contents
- push_files
- create_issue
- create_pull_request
- fork_repository
- create_branch
```

**Additional context**
Other than list_issues, many features seems to be disabled.
It looks like first 10 features only available in list_tools()?

**Comment by 0xRaduan** [comment]
@kzmszk - I do think, that you are not on the latest version of Github MCP server.

@jspahrsummers - just curious, how often do you update the officially maintained servers?

I did try to reproduce this error on my Claude Desktop, with local build and got next error though(here is a fix PR: https://github.com/modelcontextprotocol/servers/pull/305):
```
Error executing code: MCP error -32603: Invalid arguments: 6.body: Expected string, received null
```

**Comment by kzmszk** [comment]
I don't know how to check the server-github version. 

I tried with the modified mcp-client.py (https://modelcontextprotocol.io/tutorials/building-a-client).
I modified the code only to use official server-github by setting the following info.
```
server_params = StdioServerParameters(
            command="npx",
            args=["-y", "@modelcontextprotocol/server-github"],
            env={
                "GITHUB_PERSONAL_ACCESS_TOKEN": "my_token",
                "PATH": "/opt/homebrew/bin:/usr/bin:/bin"
            }
        )
```

I got the following response:
no list_issues here.
```
GitHub MCP Server running on stdio

Connected to server with tools: ['create_or_update_file', 'search_repositories', 'create_repository', 'get_file_contents', 'push_files', 'create_issue', 'create_pull_request', 'fork_repository', 'create_branch']

MCP Client Started!
Type your queries or 'quit' to exit.
```

The problem is in python_sdk **client** library? We need to get next pages or something?

**Comment by jspahrsummers** [comment]
> just curious, how often do you update the officially maintained servers?

At the moment, this is basically "whenever we remember to." Agree we need to improve this! See, e.g., https://github.com/modelcontextprotocol/servers/issues/330

**Comment by jspahrsummers** [comment]
Are you still having the original issue on the latest `main` and with https://github.com/modelcontextprotocol/servers/pull/305 merged in?

**Comment by dazzaji** [comment]
Update on tool availability after testing both npm package and local build:

**Current Status:**
1. Local build (with #305 merged):
   - Successfully exposes 16 GitHub functions
   - Can see previously unavailable tools like `add_issue_comment`
   - Issue list/search functionality now visible to Claude Desktop

2. Published npm package (via npx):
   - Still limited to original 9 tools
   - Issue list/search functionality not available
   - Appears to need updating to include recent fixes

**Remaining Issues:**
Even with local build, some functionality is still problematic:
- `add_issue_comment`: Visible but unable to add comments
- `create_or_update_file`: Can create but not update files
  - Error when updating: "MCP error -32603: Invalid arguments: content.encoding: Required, content.content: Required"

**Suggestion:**
Consider updating the published npm package to include recent fixes. Also, the remaining errors with file updates suggest possible schema validation issues that might need investigation.  I also had errors when attempting to add a comment to an existing GitHub issue.

**Comment by mikhailshilkov** [comment]
Got the same problem with npx, the docker-based server works fine. It looks like the NPM package is not up-to-date.

**Comment by cliffhall** [comment]
Deprecation Notice: Development for `server-github` has been moved to GitHub in the [http://github.com/github/github-mcp-server](https://github.com/github/github-mcp-server) repo. PRs to `server-github` in this repo are no longer being merged.
