### ISSUE TITLE
[Windows] [Claude-App] fetch-server error: timed out (encoding-issue)

### ISSUE THREAD

**Issue by SimonB97** [modelcontextprotocol/servers#57]
I ~~am~~ was getting a timed out-error when testing the fetch-server in Claude desktop:
```bash
Error getting prompt: Error: MCP error -2: Request timed out
```
---
**"was getting", because I just SOLVED it:**

Looking at the fetch-servers' logs, Claude recognized that it was a simple encoding-problem…

```powershell
PS C:\Users\sbene> Get-Content -Wait "$env:APPDATA\Claude\logs\mcp-server-fetch.log"
Installed 31 packages in 4.60s
Traceback (most recent call last):
  File "C:\Users\sbene\AppData\Local\uv\cache\archive-v0\vhYY7F_hQYeBvv3pGs-cK\Lib\site-packages\anyio\streams\memory.py", line 111, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sbene\AppData\Local\uv\cache\archive-v0\vhYY7F_hQYeBvv3pGs-cK\Lib\site-packages\anyio\streams\memory.py", line 106, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sbene\AppData\Local\uv\cache\archive-v0\vhYY7F_hQYeBvv3pGs-cK\Lib\site-packages\mcp\server\stdio.py", line 83, in stdio_server
    yield read_stream, write_stream
  File "C:\Users\sbene\AppData\Local\uv\cache\archive-v0\vhYY7F_hQYeBvv3pGs-cK\Lib\site-packages\mcp_server_fetch\server.py", line 92, in serve
    await server.run(read_stream, write_stream, options, raise_exceptions=True)
  File "C:\Users\sbene\AppData\Local\uv\cache\archive-v0\vhYY7F_hQYeBvv3pGs-cK\Lib\site-packages\mcp\server\__init__.py", line 404, in run
    async with ServerSession(
  File "C:\Users\sbene\AppData\Local\uv\cache\archive-v0\vhYY7F_hQYeBvv3pGs-cK\Lib\site-packages\anyio\_backends\_asyncio.py", line 767, in __aexit__
    raise exc_val
  File "C:\Users\sbene\AppData\Local\uv\cache\archive-v0\vhYY7F_hQYeBvv3pGs-cK\Lib\site-packages\mcp\server\__init__.py", line 407, in run
    async for message in session.incoming_messages:
  File "C:\Users\sbene\AppData\Local\uv\cache\archive-v0\vhYY7F_hQYeBvv3pGs-cK\Lib\site-packages\anyio\abc\_streams.py", line 35, in __anext__
    return await self.receive()
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sbene\AppData\Local\uv\cache\archive-v0\vhYY7F_hQYeBvv3pGs-cK\Lib\site-packages\anyio\streams\memory.py", line 119, in receive
    await receive_event.wait()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 20fb2f9cad0

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "<frozen runpy>", line 198, in _run_module_as_main
  |   File "<frozen runpy>", line 88, in _run_code
  |   File "C:\Users\sbene\AppData\Local\uv\cache\archive-v0\vhYY7F_hQYeBvv3pGs-cK\Scripts\mcp-server-fetch.exe\__main__.py", line 8, in <module>
  |   File "C:\Users\sbene\AppData\Local\uv\cache\archive-v0\vhYY7F_hQYeBvv3pGs-cK\Lib\site-packages\mcp_server_fetch\__init__.py", line 8, in main
  |     asyncio.run(serve())
  |   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
  |     return runner.run(main)
  |            ^^^^^^^^^^^^^^^^
  |   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
  |     return self._loop.run_until_complete(task)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 654, in run_until_complete
  |     return future.result()
  |            ^^^^^^^^^^^^^^^
  |   File "C:\Users\sbene\AppData\Local\uv\cache\archive-v0\vhYY7F_hQYeBvv3pGs-cK\Lib\site-packages\mcp_server_fetch\server.py", line 91, in serve
  |     async with stdio_server() as (read_stream, write_stream):
  |   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\contextlib.py", line 231, in __aexit__
  |     await self.gen.athrow(typ, value, traceback)
  |   File "C:\Users\sbene\AppData\Local\uv\cache\archive-v0\vhYY7F_hQYeBvv3pGs-cK\Lib\site-packages\mcp\server\stdio.py", line 80, in stdio_server
  |     async with anyio.create_task_group() as tg:
  |   File "C:\Users\sbene\AppData\Local\uv\cache\archive-v0\vhYY7F_hQYeBvv3pGs-cK\Lib\site-packages\anyio\_backends\_asyncio.py", line 763, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "C:\Users\sbene\AppData\Local\uv\cache\archive-v0\vhYY7F_hQYeBvv3pGs-cK\Lib\site-packages\mcp\server\stdio.py", line 75, in stdout_writer
    |     await stdout.write(json + "\n")
    |   File "C:\Users\sbene\AppData\Local\uv\cache\archive-v0\vhYY7F_hQYeBvv3pGs-cK\Lib\site-packages\anyio\_core\_fileio.py", line 108, in write
    |     return await to_thread.run_sync(self._fp.write, b)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\sbene\AppData\Local\uv\cache\archive-v0\vhYY7F_hQYeBvv3pGs-cK\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    |     return await get_async_backend().run_sync_in_worker_thread(
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\sbene\AppData\Local\uv\cache\archive-v0\vhYY7F_hQYeBvv3pGs-cK\Lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    |     return await future
    |            ^^^^^^^^^^^^
    |   File "C:\Users\sbene\AppData\Local\uv\cache\archive-v0\vhYY7F_hQYeBvv3pGs-cK\Lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    |     result = context.run(func, *args)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 19, in encode
    |     return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    | UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f605' in position 2142: character maps to <undefined>
    +------------------------------------
```

…and suggested setting the appropriate environment variable in my Claude Desktop config, based on the [llms-full.txt](https://modelcontextprotocol.io/llms-full.txt) docs:

```json
{
  "mcpServers": {
    "fetch": {
      "command": "uvx",
      "args": ["mcp-server-fetch"],
      "env": {
        "PYTHONIOENCODING": "utf-8"  # the essential modification
      }
    }
  }
}
```

Restarted Claude desktop completely, and now it works like a charm!

**Comment by SimonB97** [comment]
I still opened the issue for others to find the solution, but closing now since it's resolved.

**Comment by jspahrsummers** [comment]
Thanks for flagging! Just to make sure I understand, was this your system using a different encoding than UTF-8, or a webpage you were trying to fetch?

**Comment by SimonB97** [comment]
I'm not sure, Claude elaborated further:

"""This was a Windows system encoding issue where the MCP server was trying to write Unicode characters (specifically the emoji '\U0001f605' - 😅) to stdout but Windows was using the default cp1252 (Windows-1252) encoding instead of UTF-8."""
