### ISSUE TITLE
Brave Search unable to be attached

### ISSUE THREAD

**Issue by jacocal** [modelcontextprotocol/servers#63]
I'm running on Windows 10

This is my JSON config:

`{
    "mcpServers": {
        "brave-search": {
            "command": "npx",
            "args": [
                "@modelcontextprotocol/server-brave-search"
            ],
            "env": {
                "BRAVE_API_KEY": "MY_KEY"
            }
        },
    }
}`

This is the output from inspector:

`An error occurred: [
  {
    command: Command {
      killProcess: [Function (anonymous)],
      spawn: [Function: spawn],
      spawnOpts: [Object],
      index: 0,
      name: 'server',
      command: 'PORT= node C:\\Users\\{USER}\\AppData\\Local\\npm-cache\\_npx\\5a9d879542beca3a\\node_modules\\@modelcontextprotocol\\inspector\\server\\build\\index.js --env npx --args="-y @modelcontextprotocol/server-brave-search"',
      prefixColor: '',
      env: {},
      cwd: '',
      ipc: undefined,
      close: [Subject],
      error: [Subject],
      stdout: [Subject],
      stderr: [Subject],
      timer: [Subject],
      messages: [Object],
      process: undefined,
      subscriptions: [],
      stdin: [Socket],
      pid: 6836,
      killed: false,
      exited: false,
      state: 'exited'
    },
    index: 0,
    exitCode: 1,
    killed: false,
    timings: {
      startDate: 2024-11-26T17:55:34.422Z,
      endDate: 2024-11-26T17:55:34.435Z,
      durationSeconds: 0.0132205
    }
  },
  {
    command: Command {
      killProcess: [Function (anonymous)],
      spawn: [Function: spawn],
      spawnOpts: [Object],
      index: 1,
      name: 'client',
      command: 'PORT= node C:\\Users\\{USER}\\AppData\\Local\\npm-cache\\_npx\\5a9d879542beca3a\\node_modules\\@modelcontextprotocol\\inspector\\client\\bin\\cli.js',
      prefixColor: '',
      env: {},
      cwd: '',
      ipc: undefined,
      close: [Subject],
      error: [Subject],
      stdout: [Subject],
      stderr: [Subject],
      timer: [Subject],
      messages: [Object],
      process: undefined,
      subscriptions: [],
      stdin: [Socket],
      pid: 26384,
      killed: true,
      exited: false,
      state: 'exited'
    },
    index: 1,
    exitCode: 1,
    killed: true,
    timings: {
      startDate: 2024-11-26T17:55:34.435Z,
      endDate: 2024-11-26T17:55:34.447Z,
      durationSeconds: 0.0126171
    }
  }
]`

**Comment by mudduck** [comment]
getting same issues on windows 11/10. 

![Screenshot 2024-11-26 100333](https://github.com/user-attachments/assets/8fca290b-c143-4d7f-888d-d2ff0349ca7e)
![Screenshot 2024-11-26 100350](https://github.com/user-attachments/assets/66dd42e7-41d5-4001-a310-5c30c89f2f3d)

logs:
`2024-11-25T23:43:47.389Z [info] Attempting to connect to MCP server brave-search...
2024-11-25T23:43:47.412Z [info] Connected to MCP server brave-search!
2024-11-25T23:48:05.300Z [info] Attempting to connect to MCP server brave-search...
2024-11-25T23:48:05.335Z [info] Connected to MCP server brave-search!
2024-11-25T23:50:17.162Z [info] Attempting to connect to MCP server brave-search...
2024-11-25T23:50:17.195Z [info] Connected to MCP server brave-search!
2024-11-26T17:41:31.823Z [info] Attempting to connect to MCP server brave-search...
2024-11-26T17:41:31.852Z [info] Connected to MCP server brave-search!
2024-11-26T17:42:48.976Z [info] Attempting to connect to MCP server brave-search...
2024-11-26T17:42:49.005Z [info] Connected to MCP server brave-search!
2024-11-26T17:45:47.880Z [info] Attempting to connect to MCP server brave-search...
2024-11-26T17:45:47.909Z [info] Connected to MCP server brave-search!
2024-11-26T17:47:30.752Z [info] Attempting to connect to MCP server brave-search...
2024-11-26T17:47:30.798Z [info] Connected to MCP server brave-search!
2024-11-26T18:02:29.962Z [info] Attempting to connect to MCP server brave-search...
2024-11-26T18:02:29.985Z [info] Connected to MCP server brave-search!
2024-11-26T18:02:33.216Z [info] Attempting to connect to MCP server brave-search...
2024-11-26T18:02:33.226Z [info] Connected to MCP server brave-search!
2024-11-26T18:03:13.252Z [error] Error in MCP connection to server brave-search: SyntaxError: Unexpected token 'T', "Terminate "... is not valid JSON
    at JSON.parse (<anonymous>)
    at Vwe (C:\Users\breynolds\AppData\Local\AnthropicClaude\app-0.7.1\resources\app.asar\.vite\build\index.js:52:189)
    at qwe.readMessage (C:\Users\breynolds\AppData\Local\AnthropicClaude\app-0.7.1\resources\app.asar\.vite\build\index.js:52:115)
    at Gwe.processReadBuffer (C:\Users\breynolds\AppData\Local\AnthropicClaude\app-0.7.1\resources\app.asar\.vite\build\index.js:53:1729)
    at Socket.<anonymous> (C:\Users\breynolds\AppData\Local\AnthropicClaude\app-0.7.1\resources\app.asar\.vite\build\index.js:53:1520)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at Pipe.onStreamRead (node:internal/stream_base_commons:191:23)
`
FWIW even when connected successfully it still throws the comms error as referenced in app screen.

**Comment by dsp-ant** [comment]
> I'm running on Windows 10
> 
> This is my JSON config:
> 
> `{ "mcpServers": { "brave-search": { "command": "npx", "args": [ "@modelcontextprotocol/server-brave-search" ], "env": { "BRAVE_API_KEY": "MY_KEY" } }, } }`
> 
> This is the output from inspector:
> 
> `An error occurred: [ { command: Command { killProcess: [Function (anonymous)], spawn: [Function: spawn], spawnOpts: [Object], index: 0, name: 'server', command: 'PORT= node C:\\Users\\{USER}\\AppData\\Local\\npm-cache\\_npx\\5a9d879542beca3a\\node_modules\\@modelcontextprotocol\\inspector\\server\\build\\index.js --env npx --args="-y @modelcontextprotocol/server-brave-search"', prefixColor: '', env: {}, cwd: '', ipc: undefined, close: [Subject], error: [Subject], stdout: [Subject], stderr: [Subject], timer: [Subject], messages: [Object], process: undefined, subscriptions: [], stdin: [Socket], pid: 6836, killed: false, exited: false, state: 'exited' }, index: 0, exitCode: 1, killed: false, timings: { startDate: 2024-11-26T17:55:34.422Z, endDate: 2024-11-26T17:55:34.435Z, durationSeconds: 0.0132205 } }, { command: Command { killProcess: [Function (anonymous)], spawn: [Function: spawn], spawnOpts: [Object], index: 1, name: 'client', command: 'PORT= node C:\\Users\\{USER}\\AppData\\Local\\npm-cache\\_npx\\5a9d879542beca3a\\node_modules\\@modelcontextprotocol\\inspector\\client\\bin\\cli.js', prefixColor: '', env: {}, cwd: '', ipc: undefined, close: [Subject], error: [Subject], stdout: [Subject], stderr: [Subject], timer: [Subject], messages: [Object], process: undefined, subscriptions: [], stdin: [Socket], pid: 26384, killed: true, exited: false, state: 'exited' }, index: 1, exitCode: 1, killed: true, timings: { startDate: 2024-11-26T17:55:34.435Z, endDate: 2024-11-26T17:55:34.447Z, durationSeconds: 0.0126171 } } ]`

I suspect that this is fixed by the https://github.com/modelcontextprotocol/inspector/releases/tag/0.2.3 release

**Comment by zzworker** [comment]
{
  "mcpServers": {
    "brave-search": {
      "command": "npx",
      "args": [
        "-y",
        "@modelcontextprotocol/server-brave-search"
      ],
      "env": {
        "BRAVE_API_KEY": "xxxxxxxx"
      }
    },
    "memory": {
      "command": "npx",
      "args": [
        "-y",
        "@modelcontextprotocol/server-memory"
      ]
    },
    "filesystem": {
      "command": "npx",
      "args": [
        "-y",
        "@modelcontextprotocol/server-filesystem",
        "/Users/xxx/Downloads",
        "/Users/xxx/Code"
      ]
    }
  }
}






ERROR: You must supply a command.

Execute binaries from npm packages.

  npx [options] <command>[@version] [command-arg]...

  npx [options] [-p|--package <package>]... <command> [command-arg]...

  npx [options] -c '<command-string>'

  npx --shell-auto-fallback [shell]


Options:
  --package, -p          Package to be installed.                       [string]
  --cache                Location of the npm cache.                     [string]
  --always-spawn         Always spawn a child process to execute the command.
                                                                       [boolean]
  --no-install           Skip installation if a package is missing.    [boolean]
  --userconfig           Path to user npmrc.                            [string]
  --call, -c             Execute string as if inside `npm run-script`.  [string]
  --shell, -s            Shell to execute the command with, if any.
                                                       [string] [default: false]
  --shell-auto-fallback  Generate shell code to use npx as the "command not
                         found" fallback.
                                   [string] [choices: "", "bash", "fish", "zsh"]
  --ignore-existing      Ignores existing binaries in $PATH, or in the local
                         project. This forces npx to do a temporary install and
                         use the latest version.                       [boolean]
  --quiet, -q            Suppress output from npx itself. Subcommands will not
                         be affected.                                  [boolean]
  --npm                  npm binary to use for internal operations.
                                                              [string] [default:
  "/Users/zhuangsheng/.nvm/versions/node/v12.14.1/lib/node_modules/npm/bin/npm-c
                                                                         li.js"]
  --node-arg, -n         Extra node argument when calling a node binary.[string]
  --version, -v          Show version number                           [boolean]
  --help, -h             Show help                                     [boolean]

For the full documentation, see the manual page for npx(1).

![image](https://github.com/user-attachments/assets/e1522582-af9d-4683-9ab6-438cbf4cb4d2)

**Comment by jacocal** [comment]
@dsp-ant I'm unsure, the merge has not been officialy released, at least I'm unable to upgrade either python or uv package at the moment

**Comment by dsp-ant** [comment]
> @dsp-ant I'm unsure, the merge has not been officialy released, at least I'm unable to upgrade either python or uv package at the moment

https://www.npmjs.com/package/@modelcontextprotocol/inspector has been released.

That being said, we have seen a few people having issues with npx on windows. One way to work around this is :
```bash
# in the servers repo
npm install
npm run build
```

```json
{
  "mcpServers": {
    "brave-search": {
      "command": "node",
      "args": ["path/to/servers/src/brave-search/dist/index.js"],
      "env": {
         "BRAVE_KEY": "..."
      }
    }
  }
}
```

**Comment by natefikru** [comment]
I'm seeing this issue as well but on mac os.

**Comment by RaminMammadzada** [comment]
I am having the same issue in Mac Sonoma 14.6.1.

**Comment by ajithprabhakar** [comment]
It is the same issue for me as well, my problem is none of the mcp servers are working
<img width="383" alt="image" src="https://github.com/user-attachments/assets/25514272-1741-4562-89c3-752dd727a7a5">

**Comment by alexwhecht** [comment]
I successfully set up the Brave Search MCP server for Claude Desktop using the following steps:

1. Installed the @modelcontextprotocol/server-brave-search module globally using:

```
npm install -g @modelcontextprotocol/server-brave-search
```

2. Located the module script (dist/index.js) in the global npm directory: C:/Users/<Your_Username>/AppData/Roaming/npm/node_modules/@modelcontextprotocol/server-brave-search/dist/index.js.

3. Updated the claude_desktop_config.json file with the following configuration:

```
{
  "mcpServers": {
    "brave-search": {
      "command": "node",
      "args": [
        "C:/Users/<Your_Username>/AppData/Roaming/npm/node_modules/@modelcontextprotocol/server-brave-search/dist/index.js"
      ],
      "env": {
        "BRAVE_API_KEY": "your_api_key_here"
      }
    }
  }
}
```

4. Restarted Claude Desktop, and it now works with Brave Search MCP.

**Comment by 1WorldCapture** [comment]
> I successfully set up the Brave Search MCP server for Claude Desktop using the following steps:
> 
> 1. Installed the @modelcontextprotocol/server-brave-search module globally using:
> 
> ```
> npm install -g @modelcontextprotocol/server-brave-search
> ```
> 
> 2. Located the module script (dist/index.js) in the global npm directory: C:/Users/<Your_Username>/AppData/Roaming/npm/node_modules/@modelcontextprotocol/server-brave-search/dist/index.js.
> 3. Updated the claude_desktop_config.json file with the following configuration:
> 
> ```
> {
>   "mcpServers": {
>     "brave-search": {
>       "command": "node",
>       "args": [
>         "C:/Users/<Your_Username>/AppData/Roaming/npm/node_modules/@modelcontextprotocol/server-brave-search/dist/index.js"
>       ],
>       "env": {
>         "BRAVE_API_KEY": "your_api_key_here"
>       }
>     }
>   }
> }
> ```
> 
> 4. Restarted Claude Desktop, and it now works with Brave Search MCP.

@alexwhecht you saved my life :) two key points trying this method:
1. remember to change command from 'npx' to 'node'
2. if anyone using nvm, the path is not under your AppData, you can search `server-brave-search` using Everything, fill correct path.

**Comment by iraritchiemeek** [comment]
I had this same issue on MacOS 15.3.1

I finally got it working by installing globally `npm install -g @modelcontextprotocol/server-brave-search` and then using the following in JSON;

`{
  "mcpServers": {
    "brave-search": {
      "command": "/Users/<username>/.nvm/versions/node/v23.0.0/bin/node",
      "args": [
        "/Users/<username>/.nvm/versions/node/v23.0.0/lib/node_modules/@modelcontextprotocol/server-brave-search/dist/index.js"
      ],
      "env": {
        "BRAVE_API_KEY": "<api key>"
      }
    }
  }
}`

You can find the node executable with `which node` and the node module with `npm root -g | xargs -I {} find {} -path "*/@modelcontextprotocol/server-brave-search/dist/index.js"`
